### PR TITLE
Internal refactoring & some functional improvements of AAI

### PR DESCRIPTION
**Pull request by AlexanderSeizinger**
Functional Changes:
- Reworked selection of units (combat units as well as almost all building categories)
- Improved combat behavior
- Improved defensive behavior
- Fixed many smaller & some more severe bugs (also crashes).

Tested extensively with BA 10.24

Known limitations:
- Temporarily disabled construction of radar jammers & static artillery
- Temporarily disabled construction of air bases & metal makers (detection needs to be fixed)
- Placement of static defences needs to be improved
- Water maps are currently not working well.

### CODE REVIEW

**Comment by abma** [comment]
thank you! :-)

**Comment by abma** [comment]
doesn't compile with gcc 10.2:

```
FAILED: AI/Skirmish/AAI/CMakeFiles/AAI.dir/AAIBuildTask.cpp.o 
/usr/lib/ccache/c++ -DAAI_EXPORTS -DASIO_STANDALONE -DBUILDING_AI -DBUILDING_SKIRMISH_AI -DSPRING_DATADIR=\"/usr/local/share/games/spring\" -DSYNCCHECK -DTHREADPOOL -D_GLIBCXX_USE_NANOSLEEP -D_GNU_SOURCE=1 -D_RANDOM_TCC -D_REENTRANT -Irts -Isrc-generated/engine -Irts/ExternalAI/Interface -IAI/Wrappers -fuse-ld=gold  -std=c++17 -fdiagnostics-color=auto -march=x86-64 -msse -mfpmath=sse -mno-sse2 -mno-sse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -mno-sse4 -mno-sse4a -mno-avx -mno-fma -mno-fma4 -mno-xop -mno-lwp -mno-avx2 -fsingle-precision-constant -frounding-math -mieee-fp -pipe -fno-strict-aliasing  -fvisibility=hidden  -fvisibility-inlines-hidden -pthread  -O2      -Wformat -Wformat-security -DNDEBUG -g -fPIC   -fpic -MD -MT AI/Skirmish/AAI/CMakeFiles/AAI.dir/AAIBuildTask.cpp.o -MF AI/Skirmish/AAI/CMakeFiles/AAI.dir/AAIBuildTask.cpp.o.d -o AI/Skirmish/AAI/CMakeFiles/AAI.dir/AAIBuildTask.cpp.o -c AI/Skirmish/AAI/AAIBuildTask.cpp
In file included from AI/Skirmish/AAI/AAIMap.h:16,
                 from AI/Skirmish/AAI/AAIBuildTask.cpp:19:
AI/Skirmish/AAI/AAIMapTypes.h: In member function ‘void AAIDefenceMaps::ModifyTiles(const float3&, float, const UnitFootprint&, const AAICombatPower&, bool)’:
AI/Skirmish/AAI/AAIMapTypes.h:77:94: error: ISO C++ forbids taking the address of an unqualified or parenthesized non-static member function to form a pointer to member function.  Say ‘&AAIDefenceMaps::AddDefence’ [-fpermissive]
   77 |   void (AAIDefenceMaps::*modifyDefenceMapTile) (int , const AAICombatPower& ) = addValues ? &AddDefence : &RemoveDefence;
      |                                                                                              ^~~~~~~~~~
AI/Skirmish/AAI/AAIMapTypes.h:77:108: error: ISO C++ forbids taking the address of an unqualified or parenthesized non-static member function to form a pointer to member function.  Say ‘&AAIDefenceMaps::RemoveDefence’ [-fpermissive]
   77 |   void (AAIDefenceMaps::*modifyDefenceMapTile) (int , const AAICombatPower& ) = addValues ? &AddDefence : &RemoveDefence;
      |                                                                                                            ^~~~~~~~~~~~~
AI/Skirmish/AAI/AAIExecute.cpp: In constructor ‘AAIExecute::AAIExecute(AAI*)’:
AI/Skirmish/AAI/AAIExecute.cpp:51:97: error: ISO C++ forbids taking the address of an unqualified or parenthesized non-static member function to form a pointer to member function.  Say ‘&AAIExecute::BuildDefences’ [-fpermissive]
   51 |  m_constructionFunctions[AAIUnitCategory(EUnitCategory::STATIC_DEFENCE).GetArrayIndex()]     = &BuildDefences;
      |                                                                                                 ^~~~~~~~~~~~~
AI/Skirmish/AAI/AAIExecute.cpp:52:97: error: ISO C++ forbids taking the address of an unqualified or parenthesized non-static member function to form a pointer to member function.  Say ‘&AAIExecute::BuildArty’ [-fpermissive]
   52 |  m_constructionFunctions[AAIUnitCategory(EUnitCategory::STATIC_ARTILLERY).GetArrayIndex()]   = &BuildArty;
      |                                                                                                 ^~~~~~~~~
AI/Skirmish/AAI/AAIExecute.cpp:53:97: error: ISO C++ forbids taking the address of an unqualified or parenthesized non-static member function to form a pointer to member function.  Say ‘&AAIExecute::BuildStorage’ [-fpermissive]
   53 |  m_constructionFunctions[AAIUnitCategory(EUnitCategory::STORAGE).GetArrayIndex()]            = &BuildStorage;
      |                                                                                                 ^~~~~~~~~~~~
AI/Skirmish/AAI/AAIExecute.cpp:54:97: error: ISO C++ forbids taking the address of an unqualified or parenthesized non-static member function to form a pointer to member function.  Say ‘&AAIExecute::BuildFactory’ [-fpermissive]
   54 |  m_constructionFunctions[AAIUnitCategory(EUnitCategory::STATIC_CONSTRUCTOR).GetArrayIndex()] = &BuildFactory;
      |                                                                                                 ^~~~~~~~~~~~
AI/Skirmish/AAI/AAIExecute.cpp:55:97: error: ISO C++ forbids taking the address of an unqualified or parenthesized non-static member function to form a pointer to member function.  Say ‘&AAIExecute::BuildRadar’ [-fpermissive]
   55 |  m_constructionFunctions[AAIUnitCategory(EUnitCategory::STATIC_SENSOR).GetArrayIndex()]      = &BuildRadar;
      |                                                                                                 ^~~~~~~~~~
AI/Skirmish/AAI/AAIExecute.cpp:56:97: error: ISO C++ forbids taking the address of an unqualified or parenthesized non-static member function to form a pointer to member function.  Say ‘&AAIExecute::BuildPowerPlant’ [-fpermissive]
   56 |  m_constructionFunctions[AAIUnitCategory(EUnitCategory::POWER_PLANT).GetArrayIndex()]        = &BuildPowerPlant;
      |                                                                                                 ^~~~~~~~~~~~~~~
AI/Skirmish/AAI/AAIExecute.cpp:57:97: error: ISO C++ forbids taking the address of an unqualified or parenthesized non-static member function to form a pointer to member function.  Say ‘&AAIExecute::BuildExtractor’ [-fpermissive]
   57 |  m_constructionFunctions[AAIUnitCategory(EUnitCategory::METAL_EXTRACTOR).GetArrayIndex()]    = &BuildExtractor;
      |                                                                                                 ^~~~~~~~~~~~~~
AI/Skirmish/AAI/AAIExecute.cpp:58:97: error: ISO C++ forbids taking the address of an unqualified or parenthesized non-static member function to form a pointer to member function.  Say ‘&AAIExecute::BuildMetalMaker’ [-fpermissive]
   58 |  m_constructionFunctions[AAIUnitCategory(EUnitCategory::METAL_MAKER).GetArrayIndex()]        = &BuildMetalMaker;
      |                                                                                                 ^~~~~~~~~~~~~~~

```

**Comment by abma** [comment]
[aai.log](https://github.com/spring/AAI/files/5447205/aai.log)

**Comment by AlexanderSeizinger** [comment]
Sorry, I have been away for a few days. 

I hope the new PR fixes the compile error. With my local setup (Win7+MinGW as described in the Srping Wiki) it worked.

I tested a similar example with GCC 10.1
